# @package _global_

# AR/VR VIO Training Configuration

defaults:
  - _self_
  - data: aria_latent
  - model: arvr_vio_optimized
  - callbacks: default
  - logger: tensorboard
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null

# task name, determines output directory path
task_name: "arvr_train"

# tags to help you identify your experiments
tags: ["arvr", "vio", "experimental"]

# set False to skip model training
train: True

# evaluate on test set
test: True

# checkpoint path to resume training
ckpt_path: null

# seed for random number generators
seed: 42